### ISSUE TITLE
Additional demo pic

### ISSUE THREAD

**Issue by jaseg** [2ion/forecast#3]
Hi,

here's a (real-life-actual-camera-shittily-noisy) pic of the setup on my desk right now: http://i.imgur.com/E5iNrBT.jpg

Looks great on a 20(?) year old philips monochrome monitor with urxvt :D

Regards, jaseg

**Comment by 2ion** [comment]
Hi there, thanks for this warmly glowing, rather picturesque impression :)

Becaus of time constraints it has not been finished (or much worked on for that matter) yet, but the goal is to have a auto-updating 'monitor'-like kind of view with textual weather descriptions and diagrams together in one screen. Would look even nicer I imagine.

So long :>
