### ISSUE TITLE
Unit choice should be in config file

### ISSUE THREAD

**Issue by milouse** [2ion/forecast#6]
Currently, unit choice depends on the observed location. However, some people (like me) have absolutely NO idea of how must be interpreted imperial measures. It could be great to let the user force his/her unit choice in the config file (with auto as default choice).

**Comment by 2ion** [comment]
I totally forgot to make the CLI unit switch actual do something. That's fixed now; also a "units" option can now be set in the configuration file. Please view `forecastrc.example` for information on the key.

**Comment by milouse** [comment]
Nice :)
